### ISSUE TITLE
Request for Smoke Test (MacOS/Linux)

### ISSUE THREAD

**Issue by jetlfj** [nus-cs2103-AY2223S1/forum#230]
Hi all, would greatly appreciate some help testing my app on MacOS and Linux.
The jar file is attached [here](https://github.com/jetlfj/ip/releases/tag/A-Release) and the user guide can be found [here](https://jetlfj.github.io/ip/).
Thank you!

**Comment by carriezhengjr** [comment]
Hi, everything seems fine on my Mac!
<img width="400" alt="Screenshot 2022-09-16 at 22 23 23" src="https://user-images.githubusercontent.com/97394017/190661905-58073f56-deb6-4b99-96c0-714b1c43dd01.png">

**Comment by RezwanArefin01** [comment]
Could not get it working on Linux (Arch): 
![Screenshot_20220917_014236](https://user-images.githubusercontent.com/22095441/190700520-ed5b467b-b3c3-4b88-8467-c547c7e7a614.png)
I'm getting a ~0 width/height window, which is also not resizeable. Maybe setting a minimum size of the window will help?

**Comment by jetlfj** [comment]
> Hi, everything seems fine on my Mac! 

Thanks for testing it!

> Could not get it working on Linux (Arch)
I'm getting a ~0 width/height window, which is also not resizeable. Maybe setting a minimum size of the window will help?

Thanks for catching this, I've released a new jar file [here](https://github.com/jetlfj/ip/releases/tag/A-Release) to try to remedy it. Could you please help me test it again? Thanks!

**Comment by Nephelite** [comment]
@jetlfj 
![image](https://user-images.githubusercontent.com/97427604/190852435-f6e76c53-36aa-4223-9b6c-03ab9c82734d.png)
I ran this on a Linux VM and the images aren't displaying properly. I will refer you to this [thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/217) where RezwanArefin01 discusses the solution to this problem.

**Comment by jetlfj** [comment]
@Nephelite 
I've converted the images to .png and released the new jar file [here](https://github.com/jetlfj/ip/releases/tag/A-Release). Do you mind testing it again? Thanks!

**Comment by Nephelite** [comment]
@jetlfj Well, the images still do not display properly. This is now not a format error, but is actually image corruption. I recommend converting both images to jpg and back to png (edit: I used an online converter), then replacing your current ones. If you see that Git detects changes to the images, you'll know you succeeded. 

Edit: Just for the record, I did those steps and the images displayed properly after. 

Also, I recommend reading [this thread](https://github.com/nus-cs2103-AY2223S1/forum/issues/246) that I posted very recently, just in case.

**Comment by jetlfj** [comment]
Thank you all for the help!

Here are the changes I made:
1. Put `stage.setResizable(false);` after `stage.setScene(scene);` in `Main.java`.
2. Replaced the images after converting them again.
3. In `build.gradle`, add the following: 
```
plugins {
    // other existing plugins
    id 'org.openjfx.javafxplugin' version '0.0.10'
}

javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```
